version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: todoapp-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
    - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - todoapp

  backend:
    build: ./backend
    container_name: todoapp-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
    networks:
      - todoapp

  frontend:
    build: ./frontend
    container_name: todoapp-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - todoapp

networks:
  todoapp:

volumes:
  mysql_data:
